[WIP] Pre-allocate slices to prevent resizing at runtime
thriftrw/thriftrw-go pull request #471
Opened 2021-04-05 22:10 UTC by kanads

It was noticed that some services were spending a lot of time calling `runtime.growSlice` on the `wire.Field` slice. Additionally, most of the time on these slice resize calls were to `runtime.mallocgc`, and not to `runtime.memmove`. This hints the extra calls are commonly due to resizing smaller slice lengths.

This patch pre-allocates the slice to optimize the common case (until PR #469 is merged). Did the same in the case of reading large fields in `readBytes`.

Benchmark results:
```
name                                           old time/op    new time/op    delta
_readStruct/small_struct_with_64_fields-12     8.19µs ± 2%    6.86µs ± 4%    -16.16%  (p=0.008 n=5+5)
_readStruct/large_struct_with_512_fields-12    65.6µs ± 3%    57.2µs ± 1%    -12.74%  (p=0.008 n=5+5)

name                                           old alloc/op   new alloc/op   delta
_readStruct/small_struct_with_64_fields-12     12.0kB ± 0%    12.3kB ± 0%     +2.81%  (p=0.008 n=5+5)
_readStruct/large_struct_with_512_fields-12    98.0kB ± 0%    86.0kB ± 0%    -12.20%  (p=0.008 n=5+5)

name                                           old allocs/op  new allocs/op  delta
_readStruct/small_struct_with_64_fields-12       7.00 ± 0%      1.00 ± 0%    -85.71%  (p=0.008 n=5+5)
_readStruct/large_struct_with_512_fields-12      10.0 ± 0%       3.0 ± 0%    -70.00%  (p=0.008 n=5+5)
```

2021-04-05 22:54 UTC, abhinav requested changes

2021-04-05 22:54 UTC, abhinav commented on protocol/binary/reader.go
> +		buff.Grow(int(length))
See comment right above this block.
This is a slow path specifically for requests larger than 1MB.
Requests smaller than 1MB will be pre-allocated as desired.

2021-04-05 22:54 UTC, abhinav commented on protocol/binary/reader_benchmark_test.go
> +	}{
stylistic nit: For table tests and benchmarks, please separate the test cases from the body, and place an empty line between them:

```
benchmarks := []struct{
}{
  {
    name: "...",
    numFields: ...,
  },
  {
    // ...
  },
}

for _, bb := range benchmarks {
    b.Run(bb.name, func(b *testing.B) {
        // ...
    })
}
```

Merging the table into the for loops makes it difficult to easily scan where test cases end and where test body begins.

2021-04-05 22:54 UTC, abhinav commented on protocol/binary/reader_benchmark_test.go
> +			for i := 0; i < b.N; i++ {
When using subtests/subbenchmarks, setup specific to that benchmark/test should normally be inside the new function.

You can call b.ResetTimer to not have `NewReader(..)` count against the performance:
```suggestion
		b.Run(bench.name, func(b *testing.B) {
			reader := NewReader(constructThriftStruct(bench.numFields))
			b.ResetTImer()
			for i := 0; i < b.N; i++ {
```

2021-04-05 22:54 UTC, abhinav commented on protocol/binary/reader_benchmark_test.go
> +	boolField := []byte{byte(wire.TBool), 0, 0, 0}
The fields should typically have different field IDs.
I think this function would be more readable if we generated a wire.Struct manually and used binary.Writer to serialize it.

2021-04-06 17:15 UTC, abhinav commented on protocol/binary/reader.go
> +		buff.Grow(int(length))
Not resolved. Comment still valid.

2021-04-06 17:38 UTC, kanads commented
Fixed. Thanks.

2021-05-19 22:42 UTC, abhinav commented
Per discussion with @kanads, this ended up not actually helping. We're exploring other options.

2021-05-19 22:42 UTC, closed without merging